- name: Git Semantic Version
  id: version
  uses: PaulHatch/semantic-version@v5.0.0-alpha2
   with:
    tag_prefix: "v"
    major_pattern: "(MAJOR)"
    minor_pattern: "(MINOR)"
    format: "${major}.${minor}.${patch}-prerelease${increment}"
    bump_each_commit: true
    search_commit_body: false
    user_format_type: "json" 
